version: '3.8'
services:
  dynamodb-local:
    restart: always
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "dynamodb_data:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
volumes:
  dynamodb_data:
