version: "3"

services:
  # Prometheus (Port: 9090, Host: prometheus)
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - /docker/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    restart: always

  # Grafana
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 0.0.0.0:5000:3000
    volumes:
      - /d/workspace/.docker/monitoring/conf_grafana:/config_files
      - grafana_data:/var/lib/grafana
    environment:
      # - GF_PATHS_CONFIG=/config_files/grafana.ini
      - GF_SECURITY_ADMIN_USER=***
      - GF_SECURITY_ADMIN_PASSWORD=***
      - GF_SERVER_DOMAIN=localhost
      - GF_SERVER_HTTP_PORT=3000
    restart: always
    depends_on:
      - prometheus
    # User Define (https://grafana.com/docs/grafana/latest/installation/docker/#migrate-to-v51-or-later)
    # user: '472'
    # ADD Permission
    privileged: true

volumes:
  prometheus_data:
  grafana_data:
