# Use root/example as user/password credentials
name: mysql-comp

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ThisIsLocalDb
      MYSQL_USER: ze-cloud
      MYSQL_PASSWORD: ThisIsLocalDb
      MYSQL_DATABASE: zemotiondb
    ports:
      - 3356:3306
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db_data:
    name: mysql_db_data
