version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Seoul
      - WEBUI_PORT=8080
    volumes:
      - /X/torr/conf:/config
      - /X/torr/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 33333:33333/udp
    restart: unless-stopped
