version: "3"

services:
  redis-cluster:
    image: redis
    container_name: redis-cluster
    volumes:
      - ./conf/redis0.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    ports:
      - 6379:6379 # node-0(master)
      - 6380:6380 # node-1
      - 6381:6381 # node-2

  redis-node-1:
    network_mode: "service:redis-cluster"
    image: redis
    container_name: redis-node1
    volumes:
      - ./conf/redis1.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always

  redis-node-2:
    network_mode: "service:redis-cluster"
    image: redis
    container_name: redis-node2
    volumes:
      - ./conf/redis2.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always

  redis-cluster-entry:
    network_mode: "service:redis-cluster"
    image: redis
    container_name: redis-cluster-entry
    command: redis-cli --cluster create 127.0.0.1:6379 127.0.0.1:6380 127.0.0.1:6381 --cluster-yes
    depends_on:
      - redis-cluster
      - redis-node-1
      - redis-node-2
