name: docker-registry

services:
  registry:
    image: registry
    ports:
      - 5000:5000
    volumes:
      - ./registry-data:/var/lib/registry
      - ./conf/registry-ui.yaml:/etc/docker/registry/config.yml

  ui:
    image: joxit/docker-registry-ui
    ports:
      - 10081:80
    environment:
      - REGISTRY_TITLE=My Private Docker Registry
      - REGISTRY_URL=http://sylar-linux:5000
      - SINGLE_REGISTRY=true
    depends_on:
      - registry
