name: docker-registry

services:
  registry:
    image: registry
    ports:
      - 5000:5000
    networks:
      - registry-net

  ui:
    image: joxit/docker-registry-ui
    ports:
      - 10080:80
    environment:
      - REGISTRY_TITLE=zemotion Private Docker Registry
      - REGISTRY_URL=http://registry:5000
      - SINGLE_REGISTRY=true
    depends_on:
      - registry
    networks:
      registry-net:

networks:
  registry-net:
